#Create a VM in Azure Rajesh C S Date:23/5/2023
---
- hosts: localhost
  connection: local
  
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg-cs-ansible
        location: eastus

